spring:
  datasource:
    ds1:
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/db_jimmer?currentSchema=public&serverTimezone=Asia/Shanghai
      username: postgres
      password: postgres
    ds2:
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/db_quarkus?currentSchema=public&serverTimezone=Asia/Shanghai
      username: postgres
      password: postgres
  redis:
    host: 172.31.50.254
    port: 6379
    timeout: 10s


jimmer:
  dialect: org.babyfish.jimmer.sql.dialect.PostgresDialect
  show-sql: true
  pretty-sql: true
  database-validation-mode: NONE
